### ISSUE TITLE
Vercel Deployment

### ISSUE THREAD

**Issue by ephraimduncan** [Gerhut/visitors.vercel.app#2]
I have done everything and I am redeploying to vercel but It's taking about an hour. Did I miss something?

**Comment by Gerhut** [comment]
Have you checked the build log?

**Comment by ephraimduncan** [comment]
It finished building and deployed for the first time. But after linking the DB, I cannot redeploy.

**Comment by Gerhut** [comment]
Unfortunately it seems more like a Vercel issue but not related to this project, try simply pushing a empty commit might helps.
